# Generated by Django 3.2.14 on 2022-11-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskIdToTaskState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.BigIntegerField(default=-1)),
                ('task_state', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='username', max_length=12)),
                ('password', models.CharField(default='password', max_length=18)),
                ('email', models.CharField(default='email', max_length=350)),
                ('mobile_number', models.CharField(default='', max_length=11)),
                ('donut_number', models.IntegerField(default=0)),
                ('credit_rank', models.IntegerField(default=1)),
                ('current_exp', models.IntegerField(default=0)),
                ('dark_mode', models.BooleanField(default=False)),
                ('today_violation', models.IntegerField(default=0)),
                ('is_today_sign_in', models.BooleanField(default=False)),
                ('continue_sign_in_days', models.IntegerField(default=0)),
                ('task_info_list', models.ManyToManyField(to='CreamyBunApp.TaskIdToTaskState')),
            ],
        ),
    ]
