# Generated by Django 3.2.14 on 2022-11-05 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CreamyBunApp', '0002_auto_20221105_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(default=-1)),
                ('question_type', models.IntegerField(default=0)),
                ('description', models.CharField(default='no description', max_length=500)),
                ('must_do', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Str',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_content', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CreamyBunApp.question')),
                ('min_option_num', models.IntegerField(default=26)),
                ('max_option_num', models.IntegerField(default=0)),
                ('answer', models.ManyToManyField(to='CreamyBunApp.Str')),
                ('option_list', models.ManyToManyField(to='CreamyBunApp.KeyToValue')),
            ],
            bases=('CreamyBunApp.question',),
        ),
    ]
