# Generated by Django 3.2.14 on 2022-11-05 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CreamyBunApp', '0003_choicequestion_question_str'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillBlankQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CreamyBunApp.question')),
                ('answer', models.CharField(max_length=10000)),
            ],
            bases=('CreamyBunApp.question',),
        ),
        migrations.CreateModel(
            name='FrameSelectionQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CreamyBunApp.question')),
                ('left_up_coordinate_x', models.IntegerField(default=-1)),
                ('left_up_coordinate_y', models.IntegerField(default=-1)),
                ('right_down_coordinate_x', models.IntegerField(default=-1)),
                ('right_down_coordinate_y', models.IntegerField(default=-1)),
            ],
            bases=('CreamyBunApp.question',),
        ),
    ]
