# Generated by Django 3.2.14 on 2022-11-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreamyBunApp', '0004_fillblankquestion_frameselectionquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Int',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_content', models.IntegerField(default=-1)),
            ],
        ),
        migrations.AlterField(
            model_name='fillblankquestion',
            name='answer',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='str',
            name='str_content',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
