# 在此处定义全局常量

# 任务发布模式
NOW_RELEASE = 1
NOT_YET_RELEASE = 2
TIMED_RELEASE = 3

# problem当前状态
NOT_RECEIVED = 1
RECEIVED_BUT_NOT_FINISHED = 2
FINISHED = 3

# 任务类型常量
IMAGE = 0
TEXT = 1
VIDEO = 2
AUDIO = 3

# 作答类型常量
SINGLE_CHOICE = 0
SEVERAL_CHOICES = 1
FILL_BLANK = 2
SELECT_FRAME = 3
MULTI_TASK = 4

# 用户任务状态常量
HAS_RECEIVED = 1
HAS_POSTED = 2

# 用户分页每页任务数量
TASK_NUMBER_PER_PAGE = 10

# 选择题最多选项数
MAX_CHOICE_NUMBER = 26

# 答案字符串最长长度
MAX_ANSWER_LENGTH = 10000

# 小题题干和任务描述最长长度
MAX_DESCRIPTION_LENGTH = 500

# 任务名最长长度
MAX_TASK_NAME_LENGTH = 40

# 时间字符串长度上限
MAX_TIME_STRING_LENGTH = 25

IMAGE_TYPE_SET = {'jpg', 'bmp', 'png'}
TEXT_TYPE_SET = {'txt', 'docx'}
VIDEO_TYPE_SET = {'mp4'}
AUDIO_TYPE_SET = {'mp3', 'wav'}
ALL_TYPE_SET = IMAGE_TYPE_SET | TEXT_TYPE_SET | VIDEO_TYPE_SET | AUDIO_TYPE_SET
TYPE_SET = [IMAGE_TYPE_SET, TEXT_TYPE_SET, VIDEO_TYPE_SET, AUDIO_TYPE_SET, ALL_TYPE_SET]
